server:
  port: 9191
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:phonebook
    username: sa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

phonebook:
  messages:
    saveSucc: Contact Saved Successfully
    updateSucc: Contact Updated Successfully
    saveFail: Failed to Save Contact
   